# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll scalability test with tags
baseurl: "/jekyll-scalability-test-tags" # the subpath of your site, e.g. /blog
url: "http://riccardo.casatta.it" # the base hostname & protocol for your site
twitter_username: RCasatta
github_username:  rcasatta

# Build settings
markdown: kramdown


github:
  repo: https://github.com/RCasatta/jekyll-scalability-test-tags
  editpost: https://github.com/RCasatta/jekyll-scalability-test-tags/edit/gh-pages/
